mindmap
  root((Logistics System))
    Authentication
      Login Page (login.php)
      Register Page (register.php)
        ::icon(fa fa-key)
        [Secret Code Required]
    
    Dashboard (index.php)
      ::icon(fa fa-home)
      
      Jobs Management
        View All Jobs (search_jobs.php)
        Create Job (add_job.php)
        Actions
            ::icon(fa fa-cogs)
            Delete Job (Admin Only)
      
      Site Management (manage_sites.php)
        View Sites Table
        Add Site (Modal)
        Edit Site (Modal)
            ::icon(fa fa-edit)
            [Update Address & Fleet Targets]
            
      Fleet Management (manage_vehicles.php)
        View Fleet Table
        Add Vehicle (Modal)
            ::icon(fa fa-truck)
      
      User Account
        ::icon(fa fa-user)
        Logout (actions/logout.php)